### ISSUE TITLE
Auto play no working

### ISSUE THREAD

**Issue by fireplace009** [mpachnis/mp-slider#3]
Is this feature implemented or am I doing it wrong ?

```
<mp-slider controls bullets auto-play >
...
</mp-slider>
```

**Comment by mpachnis** [comment]
Thanks for noticed that. Will fix it

**Comment by mpachnis** [comment]
Please re-download the element with bower or git, you can also change the interval time (default is 5000ms)

```
<mp-slider controls bullets auto-play interval=10000></mp-slider>
```

**Comment by fireplace009** [comment]
Great! Thank you 😊
