### ISSUE TITLE
Your component is featured in a Vaadin blog

### ISSUE THREAD

**Issue by binbalenci** [mpachnis/mp-slider#4]
Hi mpachnis,

I have tested your component and I really liked it. I have featured it on the blog [8 best Polymer carousel web components for your next web app](https://vaadin.com/blog/10-best). It would be awesome to have some words from the original author in the comment section or on this [tweet](https://twitter.com/binhbbbb) or both.

Cheers!

**Comment by mpachnis** [comment]
Hi Binh,

Thanks for sharing my component.
