### ISSUE TITLE
Issue with bullets/thumbs on auto play

### ISSUE THREAD

**Issue by acsadam0404** [mpachnis/mp-slider#6]
https://codepen.io/acsadam0404/pen/eLLwKe

```
mp-slider.html:242 Uncaught TypeError: Cannot read property 'getElementsByTagName' of null
    at HTMLElement._changeBullet (mp-slider.html:242)
    at _autoInternal.setInterval (mp-slider.html:306)
```

When you use auto play but disable bullets or thumbs there is a javascript error.

```
   _autoPlaySlider() 
```

references 

```
  this._changeBullet();
  this._changeThumb();
```

and neither of them checks for the existence of the item itself.

**Comment by mpachnis** [comment]
Thanks for reporting this. This is now fixed.

**Comment by acsadam0404** [comment]
Thanks for the quick fix and the nice addon! I can confirm the bug is gone now. I'm using it in my vaadin flow project with webjars.
