### ISSUE TITLE
Ability to hide pause on hover

### ISSUE THREAD

**Issue by acsadam0404** [mpachnis/mp-slider#7]
There is a _pauseOnHover property which is not used anywhere as far as I can see. I tried setting the pause-color to transparent, but that didn't work either. Is there any way to hide the pause icon? Thanks in advance.

**Comment by mpachnis** [comment]
This property it was for something else, but never implemented. I'll add a new to show the pause icon.

**Comment by mpachnis** [comment]
I add a new property show-pause-icon, by default is false so the icon is hidden. I also fix the custom styles.

**Comment by acsadam0404** [comment]
Thank you for the quick action, you are the best!

**Comment by acsadam0404** [comment]
@mpachnis just tried your modifications. The pause button is gone, but that causes an error in this line:

```
 this.$.slider.querySelector('#pauseIcon').style.opacity = 0;
```

since the pauseIcon is not there in the dom.

```
Uncaught TypeError: Cannot read property 'style' of null
    at HTMLElement._resumeAutoPlay (mp-slider.html:333)
    at HTMLDivElement.handler (template-stamp.html:92)
```

**Comment by mpachnis** [comment]
Fixed

**Comment by acsadam0404** [comment]
I need a new version, created a pull request to try to help your work. Could you check it please?

**Comment by mpachnis** [comment]
Are you still having issue with this one? No need to change the version, I update the v2.0.4 tag with the fix.

(tag v2.0.4)[https://github.com/mpachnis/mp-slider/commit/0a1ae7bb3ef96a226259478b064146cd1d3a00af]

**Comment by acsadam0404** [comment]
I'm using it in a vaadin project with https://www.webjars.org/ . If I deploy it to webjars it says:

```
WebJar org.webjars.bowergithub.mpachnis mp-slider 2.0.4 has already been deployed
```

so I can't update the version there.

**Comment by mpachnis** [comment]
New version it is.
